style                            = "default"
indent                           = 4
margin                           = 92
always_for_in                    = true
remove_extra_newlines            = true
pipe_to_function_call            = true
short_to_long_function_def       = true
separate_kwargs_with_semicolon   = true
