name = "SentryIntegration"
uuid = "0c0dc41a-7892-49ef-a372-46007ef8f0a8"
authors = ["Daniel Cocks <daniel.cocks@gmail.com>"]
version = "0.2.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
